// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcm0H1JJtftNE5A-ToyGjHNHQCysBESs',
    appId: '1:478637173540:web:55c5df774d50bbe3aee1b1',
    messagingSenderId: '478637173540',
    projectId: 'carservices-d9b9d',
    authDomain: 'carservices-d9b9d.firebaseapp.com',
    storageBucket: 'carservices-d9b9d.firebasestorage.app',
    measurementId: 'G-N7S0CW8VTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_eg3LumpiXmc1CwJV7iakWEBzhHd3bU',
    appId: '1:478637173540:android:666ded06c1da39f8aee1b1',
    messagingSenderId: '478637173540',
    projectId: 'carservices-d9b9d',
    storageBucket: 'carservices-d9b9d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZcm0H1JJtftNE5A-ToyGjHNHQCysBESs',
    appId: '1:478637173540:web:6669497d4b564555aee1b1',
    messagingSenderId: '478637173540',
    projectId: 'carservices-d9b9d',
    authDomain: 'carservices-d9b9d.firebaseapp.com',
    storageBucket: 'carservices-d9b9d.firebasestorage.app',
    measurementId: 'G-28S7P9ZXQ6',
  );
}
